const reasonLabels: Record<string, string> = {
  POLICY_APPLICABLE: '현재 요청에 적용할 정책을 확인했습니다.',
  POLICY_INCOMPLETE: '필수 정책 조건이 완전하지 않아 담당자 확인이 필요합니다.',
  HUMAN_REVIEW_REQUIRED: '자동 판정만으로 완료할 수 없어 담당자 검토가 필요합니다.',
  PURPOSE_SCOPE_MISMATCH: '승인된 업무 목적과 실제 요청 목적이 일치하지 않습니다.',
  UNAPPROVED_DATA_CLASS: '승인 범위에 포함되지 않은 데이터 유형이 요청되었습니다.',
  SENSITIVE_SCOPE_DENIED: '민감정보 사용 범위가 승인 조건을 벗어났습니다.',
  EXTERNAL_DESTINATION_DENIED: '승인되지 않은 외부 전송 대상으로 요청되었습니다.',
  DIGITAL_ASSET_APPROVED_AMOUNT_EXCEEDED: '요청 금액이 승인된 최대 금액을 초과했습니다.',
  DIGITAL_ASSET_APPROVED_ASSET_MISMATCH: '요청 자산이 승인된 자산과 일치하지 않습니다.',
  DIGITAL_ASSET_APPROVED_DESTINATION_MISMATCH: '실행 목적지가 승인된 목적지와 일치하지 않습니다.',
  DIGITAL_ASSET_APPROVED_BENEFICIARY_MISMATCH: '수취인이 승인된 수취인과 일치하지 않습니다.',
  DIGITAL_ASSET_APPROVED_PERIOD_VIOLATION: '요청 시점이 승인된 실행 기간을 벗어났습니다.',
  SENSITIVE_DATA_REFLECTION: '외부 AI 응답에서 민감정보 반영이 탐지되어 전달을 차단했습니다.',
  RESPONSE_SENSITIVE_DATA_DETECTED: '외부 AI 응답에서 민감정보가 탐지되었습니다.',
  RAW_VALUE_REFLECTION: '보호 대상 원값이 외부 응답에 반영되었습니다.',
  CONNECTOR_NOT_EXECUTED: '외부 Provider 호출이 실행되지 않았거나 결과를 확인하지 못했습니다.',
  SUBJECT_SCOPE_MISMATCH: '승인된 대상과 실제 실행 대상이 일치하지 않습니다.',
  AI_FIXED_CONDITIONS_MISMATCH: '동결된 평가 조건과 실제 실행 조건이 일치하지 않습니다.',
  EVALUATION_EXECUTION_NOT_STARTED: '등록된 평가 실행이 아직 시작되지 않았습니다.',
  EVALUATION_MATRIX_INCOMPLETE: '필요한 평가 case와 모델 실행이 모두 수집되지 않았습니다.',
  EVALUATION_PROVENANCE_MISMATCH: '저장된 실행 증적과 현재 평가 계약의 출처 정보가 일치하지 않습니다.',
  EVALUATION_MODEL_MISMATCH: '저장된 실행의 모델 설정이 현재 평가 계약과 일치하지 않습니다.',
  EVALUATION_EXECUTION_MISSING: '해당 case와 모델 조합의 실행 증적이 없습니다.',
  RUN_VERSION_MISMATCH: '실행에 기록된 평가 Run 버전이 현재 등록 버전과 일치하지 않습니다.',
  CONTRACT_DIGEST_MISMATCH: '평가 계약 Digest가 현재 등록된 계약과 일치하지 않습니다.',
  DATASET_ID_MISMATCH: '실행에 사용한 데이터셋 ID가 평가 계약과 일치하지 않습니다.',
  DATASET_VERSION_MISMATCH: '실행에 사용한 데이터셋 버전이 평가 계약과 일치하지 않습니다.',
  DATASET_DIGEST_MISMATCH: '실행 데이터셋 Digest가 평가 계약과 일치하지 않습니다.',
  POLICY_SNAPSHOT_MISMATCH: '정책 Snapshot이 현재 평가 계약과 일치하지 않습니다.',
  EXPECTED_INPUT_DIGEST_MISMATCH: '평가가 기대한 입력 Digest가 현재 계약과 일치하지 않습니다.',
  ACTUAL_INPUT_DIGEST_MISMATCH: '실제 실행 입력 Digest가 평가 계약과 일치하지 않습니다.',
  MODEL_PROFILE_VERSION_MISMATCH: '실행 모델 Profile 버전이 현재 등록 버전과 일치하지 않습니다.',
  MODEL_PROFILE_DIGEST_MISMATCH: '모델 Profile Digest가 현재 등록값과 일치하지 않습니다.',
  PROVIDER_MODEL_MISMATCH: '외부 Provider에 요청한 모델이 승인된 모델과 일치하지 않습니다.',
  PROVIDER_MODEL_VERSION_MISMATCH: '외부 Provider 모델 버전이 승인된 버전과 일치하지 않습니다.',
  CONNECTION_PROFILE_MISMATCH: 'Provider 연결 Profile이 평가 계약과 일치하지 않습니다.',
  MAX_TOKENS_MISMATCH: '실행의 최대 Token 설정이 승인된 조건과 일치하지 않습니다.',
  TEMPERATURE_MISMATCH: '실행의 Temperature 설정이 승인된 조건과 일치하지 않습니다.',
  SAMPLING_PROFILE_MISMATCH: '실행의 Sampling Profile이 승인된 조건과 일치하지 않습니다.',
  DESTINATION_PROFILE_DIGEST_MISMATCH: '외부 전송 대상 Profile Digest가 현재 등록값과 일치하지 않습니다.',
  EVIDENCE_INCOMPLETE: '실행 증적이 완전하게 수집되지 않았습니다.',
};

export function reasonDisplayName(reasonCode: string) {
  return reasonLabels[reasonCode] ?? '연결된 정책 또는 실행 통제 조건을 확인해야 합니다.';
}
